# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Create env file
      run: |
        touch .env
        echo REACT_APP_PROD_API=${REACT_APP_PROD_API} >> .env
        echo REACT_APP_PROD_ADMIN_API=${REACT_APP_PROD_ADMIN_API} >> .env
        echo REACT_APP_PROD_FILINGSOLUTIONS_API=${REACT_APP_PROD_FILINGSOLUTIONS_API} >> .env
        echo REACT_APP_ACCESS_TOKEN=${REACT_APP_ACCESS_TOKEN} >> .env
        
        cat .env
      env: 
        REACT_APP_PROD_API: ${{ secrets.REACT_APP_PROD_API }} 
        REACT_APP_PROD_ADMIN_API: ${{ secrets.REACT_APP_PROD_ADMIN_API }} 
        REACT_APP_PROD_FILINGSOLUTIONS_API: ${{ secrets.REACT_APP_PROD_FILINGSOLUTIONS_API }} 
        REACT_APP_ACCESS_TOKEN: ${{ secrets.REACT_APP_ACCESS_TOKEN }} 


        
    - run: yarn install
    - run: CI=false NODE_OPTIONS="--max-old-space-size=4096" yarn run build --if-present

